# Generated by Django 4.0 on 2021-12-29 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=255)),
                ('name1', models.CharField(blank=True, max_length=50, null=True)),
                ('name2', models.CharField(blank=True, max_length=50, null=True)),
                ('kana1', models.CharField(blank=True, max_length=50, null=True)),
                ('kana2', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('birthday', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('buildingName', models.CharField(blank=True, max_length=50, null=True)),
                ('verificationcode', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('userstatus', models.IntegerField(default=0)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
