# Generated by Django 4.0 on 2022-01-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address1',
            new_name='charger_phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address2',
            new_name='charger_prefecture',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='choice_word',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='buildingName',
            new_name='company_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='kana1',
            new_name='coporate_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='kana2',
            new_name='corporate_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name1',
            new_name='corporate_building_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name2',
            new_name='corporate_city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='corporate_country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='street',
            new_name='corporate_estable_date',
        ),
        migrations.AddField(
            model_name='user',
            name='corporate_fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='corporate_furigana',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='corporate_homepage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='corporate_mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='corporate_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='corporate_prefecture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='corporate_zipcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname_of_charger',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname_of_charger_firagana',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname_of_charger',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname_of_charger_firagana',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
