# Generated by Django 4.0 on 2022-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdmgroupdmlistmodel',
            name='contact_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perdmgroupdmlistmodel',
            name='mailaddress',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='perdmgroupdmlistmodel',
            name='site_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
