# Generated by Django 4.0 on 2022-03-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0002_alter_perdmgroupdmlistmodel_contact_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmtextsetmodel',
            name='dmTitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dmtextsetmodel',
            name='text2000',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dmtextsetmodel',
            name='recent_send_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dmtextsetmodel',
            name='register_date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stoplinksettingmodel',
            name='contact_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stoplinksettingmodel',
            name='site_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
