# Generated by Django 4.0 on 2022-01-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0002_rename_address1_user_charger_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='corporate_address_room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
