# Generated by Django 4.0 on 2022-01-06 15:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0003_user_corporate_address_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMailSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sendmail', models.CharField(blank=True, max_length=50, null=True)),
                ('replytodmail', models.CharField(blank=True, max_length=50, null=True)),
                ('smtp', models.CharField(blank=True, max_length=50, null=True)),
                ('mailid', models.CharField(blank=True, max_length=50, null=True)),
                ('mailpwd', models.CharField(blank=True, max_length=50, null=True)),
                ('mailport', models.CharField(blank=True, max_length=50, null=True)),
                ('mailssl', models.CharField(blank=True, max_length=50, null=True)),
                ('popcheck', models.CharField(blank=True, max_length=50, null=True)),
                ('popserver', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('userpwd', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_mail_setting', to='AutoFill.user')),
            ],
        ),
    ]
