# Generated by Django 4.0 on 2022-01-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0004_sendmailsetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendMailSetting',
            new_name='SendMailSettingModel',
        ),
    ]
