# Generated by Django 4.0 on 2022-01-07 03:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0005_rename_sendmailsetting_sendmailsettingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopLinkSettingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mailaddress', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_url', models.CharField(blank=True, max_length=50, null=True)),
                ('site_url', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=50, null=True)),
                ('auto_manual', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_link_setting', to='AutoFill.user')),
            ],
        ),
    ]
