# Generated by Django 4.0 on 2022-01-08 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0006_stoplinksettingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmClickedCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clickednum', models.IntegerField(default=0)),
                ('mailid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
