# Generated by Django 4.0 on 2022-01-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0007_dmclickedcount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DmClickedCount',
            new_name='DmClickedCountModel',
        ),
    ]
