# Generated by Django 4.0 on 2022-01-08 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0008_rename_dmclickedcount_dmclickedcountmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailDeliveryStopTextsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text2000', models.CharField(blank=True, max_length=50, null=True)),
                ('text1000', models.CharField(blank=True, max_length=50, null=True)),
                ('text500', models.CharField(blank=True, max_length=50, null=True)),
                ('text250', models.CharField(blank=True, max_length=50, null=True)),
                ('text100', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_text_setting', to='AutoFill.user')),
            ],
        ),
    ]
