# Generated by Django 4.0 on 2022-01-08 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0009_maildeliverystoptextsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesurmentMethodSettingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mesurment_method', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesurment_setting', to='AutoFill.user')),
            ],
        ),
    ]
