# Generated by Django 4.0 on 2022-01-11 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0010_mesurmentmethodsettingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMtextSetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title50', models.TextField(blank=True, null=True)),
                ('title25', models.TextField(blank=True, null=True)),
                ('title10', models.TextField(blank=True, null=True)),
                ('text1000', models.TextField(blank=True, null=True)),
                ('text500', models.TextField(blank=True, null=True)),
                ('text100', models.TextField(blank=True, null=True)),
                ('register_date', models.CharField(blank=True, max_length=50, null=True)),
                ('recent_send_date', models.CharField(blank=True, max_length=50, null=True)),
                ('sent_count', models.FloatField(default=0)),
                ('click_rate', models.FloatField(default=0)),
                ('total_count', models.FloatField(default=0)),
                ('average_count', models.FloatField(default=0)),
                ('text250', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmtext_setting', to='AutoFill.user')),
            ],
        ),
    ]
