# Generated by Django 4.0 on 2022-01-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0011_dmtextsetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmtextsetmodel',
            name='text250',
            field=models.TextField(blank=True, null=True),
        ),
    ]
