# Generated by Django 4.0 on 2022-01-13 08:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0012_alter_dmtextsetmodel_text250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildeliverystoptextsmodel',
            name='text100',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='maildeliverystoptextsmodel',
            name='text1000',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='maildeliverystoptextsmodel',
            name='text2000',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='maildeliverystoptextsmodel',
            name='text250',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='maildeliverystoptextsmodel',
            name='text500',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='DMGroupModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('subjectcount', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmgroup', to='AutoFill.user')),
            ],
        ),
    ]
