# Generated by Django 4.0 on 2022-01-13 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0013_alter_maildeliverystoptextsmodel_text100_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmgroupmodel',
            name='subjectcount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PerDMGroupDmListModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mailaddress', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_url', models.CharField(blank=True, max_length=50, null=True)),
                ('site_url', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=50, null=True)),
                ('auto_manual', models.CharField(blank=True, max_length=50, null=True)),
                ('dmgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_group', to='AutoFill.dmgroupmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_dmgroup_list', to='AutoFill.user')),
            ],
        ),
    ]
