# Generated by Django 4.0 on 2022-01-25 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0015_perdmgroupdmlistmodel_last_sent_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMSendStatusModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('list_table_id', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_send_status', to='AutoFill.user')),
            ],
        ),
    ]
