# Generated by Django 4.0 on 2022-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0016_dmsendstatusmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmsendstatusmodel',
            name='reserve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmsendstatusmodel',
            name='specific_day',
            field=models.TextField(blank=True, null=True),
        ),
    ]
