# Generated by Django 4.0 on 2022-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0017_dmsendstatusmodel_reserve_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmsendstatusmodel',
            name='reserve_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
