# Generated by Django 4.0 on 2022-01-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0018_alter_dmsendstatusmodel_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmsendstatusmodel',
            name='reserve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
