# Generated by Django 4.0 on 2022-01-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0019_alter_dmsendstatusmodel_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmsendstatusmodel',
            name='text_option',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dmsendstatusmodel',
            name='textpattern1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmsendstatusmodel',
            name='textpattern2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
