# Generated by Django 4.0 on 2022-01-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0020_dmsendstatusmodel_text_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_statu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='expirydate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paydate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
