# Generated by Django 4.0 on 2022-01-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0021_user_account_statu_user_expirydate_user_paydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
