# Generated by Django 4.0 on 2022-01-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0022_alter_user_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_pay_statu',
            field=models.IntegerField(default=0),
        ),
    ]
