# Generated by Django 4.0 on 2022-01-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0023_user_initial_pay_statu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='price_plan',
            field=models.IntegerField(default=1),
        ),
    ]
