# Generated by Django 4.0 on 2022-02-03 05:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0024_user_payment_method_user_price_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_inquiry_send_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_mail_send_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_send_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_send_faild_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_send_success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initial_amount', models.FloatField(blank=True, null=True)),
                ('monthly_amount', models.FloatField(blank=True, null=True)),
                ('initial_pay_date', models.DateTimeField(blank=True, null=True)),
                ('monthly_pay_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('editer', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_user', to='AutoFill.user')),
            ],
        ),
    ]
