# Generated by Django 4.0 on 2022-02-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0025_user_total_inquiry_send_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesurmentmethodsettingmodel',
            name='click_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
