# Generated by Django 4.0 on 2022-02-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoFill', '0027_alter_user_corporate_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='corporate_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
